root: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true
    destructuring: true
    spread: true

env:
  browser: true

plugins:
  - react

extends: airbnb

rules:
  func-names: off
  no-unused-vars: warn
  semi: [warn, never]
  new-cap: off
  quotes: [warn, single]
  react/prop-types: warn
  react/prefer-stateless-function: off
